### ISSUE TITLE
p-value bug in volcano

### ISSUE THREAD

**Issue by grandrea** [ieoresearch/QProMS#19]
Hello, I am doing volcano and select p-value BH correction with alpha 0.05. Thus, i expect the cutoff to be at -log10(0.05) = 1.3 on the y axis. It is much higher

![image](https://github.com/user-attachments/assets/0368b018-47d7-49c5-86ac-0000064cb3d3)

@FabioBedin

**Comment by grandrea** [comment]
ah, the truncation is fdr corrected but the values plotted are not the fdr corrected p values... very confusing... wouldn't it be correct to plot p.adjust and truncate at FDR=0.05? asking cos genuinely curious

**Comment by FabioBedin** [comment]
In my opinion, it is always better to use raw p-value to generate a volcano plot. The p-values are the basic values from which adjusted methods are computed and it is typically better to plot basic data rather than derived ones. Note that there is always a p-value cutoff that corresponds to any p.adj cutoff, so using it as y-axis has no advantage that I can think of. This is the reason why I always use the raw p-value for the plot.

**Comment by grandrea** [comment]
fair enough will edit readme to make this a bit more clear
